services:
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=tutu
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: postgres_tutu
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 80
    container_name: pgadmin_tutu
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - 15432:80
    depends_on:
      - postgres

volumes:
  postgres:
  pgadmin:
